import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Providers } from '@/components/Providers';
import Navigation from '@/components/Navigation';
import '@/styles/globals.css';
import styles from '@/styles/page.module.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Navigation />
          <div className={styles.page}>
            <main className={styles.main}>
              <div className='flex w-[600px] flex-col items-center gap-5 rounded-large bg-default-50 py-8 shadow-small'>
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
